# Generated by Django 4.2 on 2023-05-16 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("college", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Stream",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250, unique=True)),
                ("slug", models.SlugField(max_length=250, unique=True)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "stream",
                "verbose_name_plural": "streams",
                "ordering": ("name",),
            },
        ),
        migrations.RemoveField(
            model_name="department",
            name="description",
        ),
    ]
